name:  Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
      
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install libncurses-dev
        
      - name: Run make
        run: make
